// Code generated by scripts/gen-contract-tokens.mjs from contract/tokens.json — DO NOT EDIT.
// 双端共享数值契约（codebase-review-plan.md A2 第二步）：Web（client/src/contract-tokens.js）与 Android（ContractTokens.kt）以及服务端参考实现（overlay-merge.js）都以本文件为唯一事实来源。改数值请改这里，再运行 `npm run contract:tokens:write` 重生成双端产物，提交前保证 `npm run contract:tokens`（生成物与契约 diff 核对）通过。颜色属视觉层（design-tokens.json / MapVisualTokens 管线），不入本契约。
package com.historymap.app

/**
 * 双端共享数值契约（Web 版 client/src/contract-tokens.js 同源）：
 * 投影 fitSize、LOD 档位矩阵、碰撞参数、kind 白名单、设置项 schema（分类 + 播放速度）。
 * 唯一事实来源：contract/tokens.json（由 scripts/gen-contract-tokens.mjs 生成，勿手改；
 * 改契约 → node scripts/gen-contract-tokens.mjs --write 并保持 npm run contract:tokens 通过）。
 */
object ContractTokens {

    /** 投影标定宽高（d3-geo geoMercator fitSize / MercatorProjection.fit 的 1000×800） */
    const val PROJECTION_FIT_WIDTH: Double = 1000.0
    const val PROJECTION_FIT_HEIGHT: Double = 800.0

    /** LOD 档位滞回（±，缩放临界抖动防反复换档） */
    const val LOD_HYSTERESIS: Float = 0.02f

    /** LOD 档位下界（降序：[L0下界, L1下界, L2下界]；s ≥ 下界即落在该档或更「全国」） */
    val LOD_THRESHOLDS: FloatArray = floatArrayOf(0.4f, 0.24f, 0.13f)

    /** 碰撞推挤参数（泡泡间留白 / 单方向最大推挤量 / 视口回收边距） */
    const val COLLISION_GAP: Float = 6f
    const val COLLISION_MAX_PUSH: Float = 64f
    const val COLLISION_VIEWPORT_PAD: Float = 6f

    /** 地点类要素 kind 白名单（都城/战场/书院 → 响应顶层 properties.places） */
    val PLACE_KINDS: Set<String> = setOf("capital", "battlefield", "academy")

    /** 事件分类定义（id + 全称 + 时间轴短标签） */
    data class CategoryDef(val id: String, val label: String, val labelShort: String)

    val CATEGORIES: List<CategoryDef> = listOf(
        CategoryDef("era", "时代格局", "政治"),
        CategoryDef("figure", "名人轨迹", "人物"),
        CategoryDef("military", "军事·领土", "军事"),
        CategoryDef("economy", "经济变革", "经济"),
        CategoryDef("invention", "重要发明", "文化"),
    )

    /** 分类 id → 全称（设置面板 / 详情面板 / 事件流） */
    val CATEGORY_LABELS: Map<String, String> = CATEGORIES.associate { it.id to it.label }

    /** 分类 id → 时间轴图例短标签 */
    val CATEGORY_SHORT_LABELS: Map<String, String> = CATEGORIES.associate { it.id to it.labelShort }

    /** 合法分类 id 集合（设置校验） */
    val CATEGORY_IDS: Set<String> = CATEGORIES.map { it.id }.toSet()

    /** 播放速度档位 → tickMs(ms) */
    val SPEED_TICK_MS: Map<String, Long> = mapOf("slow" to 40L, "normal" to 20L, "fast" to 10L)
    const val SPEED_TICK_NORMAL: Long = 20L
    val SPEED_IDS: Set<String> = SPEED_TICK_MS.keys
}
